language: node_js
os: linux
dist: trusty
node_js:
  - 8
  - 10
sudo: required
addons:
  firefox: latest
  apt:
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules

before_install:
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  # Symlink closure library used by test/jsunit
  - ln -s $(npm root)/google-closure-library ../closure-library
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2

script:
  - set -x
  - npm test
  - cd tests/compile; compile.sh; cd ../..
  # - tests/run_all_tests.sh

before_deploy:
  - npm i -g

deploy:
  provider: npm
  email: kindscript@microsoft.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: develop
